# Generated by Django 5.2.17 on 2026-08-15 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('expenses', '0002_expense'),
        ('finance', '0002_accounttransaction'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel (High-Speed Diesel)'), ('PETROL', 'Petrol / Gasoline'), ('ENGINE_OIL', 'Engine Oil (Lubricant)'), ('HYDRAULIC_OIL', 'Hydraulic Oil / Transmission Fluid')], db_index=True, default='DIESEL', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Volume in Litres', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Rate per Litre in INR', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Authoritative total = quantity * unit_price (calculated server-side)', max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('UPI', 'UPI / QR Code'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit / Pay Later (Supplier Payable)')], db_index=True, default='CASH', max_length=20)),
                ('meter_reading', models.DecimalField(decimal_places=2, help_text='Machine meter reading at refueling (Hours or KM)', max_digits=10)),
                ('reference_no', models.CharField(blank=True, help_text='Bill / Slip / Invoice No.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_entries', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fuel_entries', to=settings.AUTH_USER_MODEL)),
                ('linked_expense', models.OneToOneField(help_text='Enforces 1:1 database constraint between Fuel Entry and Expense', on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_entry', to='expenses.expense')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='machines.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='employees.employee')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Fuel & Lubricant Entry',
                'verbose_name_plural': 'Fuel & Lubricant Entries',
                'db_table': 'fuel_entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
