# Generated by Django 5.2.17 on 2026-08-15 10:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Machine Type',
                'verbose_name_plural': 'Machine Types',
                'db_table': 'machine_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(help_text='Equipment name / Model (e.g. John Deere 5310)', max_length=100)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Ready for Work'), ('UNDER_MAINTENANCE', 'Under Maintenance / In Workshop'), ('IDLE', 'Idle / Parked'), ('DECOMMISSIONED', 'Decommissioned / Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('current_meter_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current meter reading (Hour meter or Odometer)', max_digits=10)),
                ('meter_unit', models.CharField(choices=[('HOURS', 'Hour Meter (Hours)'), ('KM', 'Odometer (Kilometers)')], db_index=True, default='HOURS', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_machines', to='employees.employee')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinetype')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'machines',
                'ordering': ['machine_code'],
            },
        ),
    ]
