# Generated by Django 5.2.17 on 2026-08-16 09:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeepayment_units_logged_and_more'),
        ('finance', '0004_dailyclosing'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('billing_type', models.CharField(choices=[('TIME_HOURLY', 'Time-Based (Hourly) - Harvester'), ('ACRE', 'Acre-Based - Tractor'), ('PIECE', 'Piece-Based - Tractor')], db_index=True, default='TIME_HOURLY', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Break duration in hours', max_digits=5)),
                ('net_working_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated net working hours = (end_time - start_time) - break_hours', max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commercial rate per hour in INR', max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Number of Acres or Pieces', max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per unit (Acre/Piece) in INR', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Authoritative total bill amount in INR', max_digits=15)),
                ('start_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Machine meter reading at start of work', max_digits=10, null=True)),
                ('end_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Machine meter reading at end of work', max_digits=10, null=True)),
                ('meter_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Machine usage delta = end_meter - start_meter (for service/maintenance only)', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_machine_work_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_work_entries', to='finance.customer')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to='machines.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_work_entries', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Machine Work Entry',
                'verbose_name_plural': 'Machine Work Entries',
                'db_table': 'machine_work_entries',
                'ordering': ['-work_date', '-id'],
            },
        ),
    ]
