# Generated by Django 5.2.17 on 2026-08-16 10:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeepayment_units_logged_and_more'),
        ('finance', '0004_dailyclosing'),
        ('machines', '0002_machineworkentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('requested_start_time', models.TimeField(blank=True, null=True)),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated quantity (Acres or Pieces)', max_digits=10)),
                ('expected_duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated duration in hours', max_digits=5)),
                ('billing_type', models.CharField(choices=[('TIME_HOURLY', 'Time-Based (Hourly) - Harvester'), ('ACRE', 'Acre-Based - Tractor'), ('PIECE', 'Piece-Based - Tractor')], db_index=True, default='TIME_HOURLY', max_length=20)),
                ('work_location', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_description', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed & Scheduled'), ('DISPATCHED', 'Dispatched to Field'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Work Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('dispatch_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_machine_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_bookings', to='finance.customer')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='machines.machine')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='machines.machinetype')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_bookings', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Machine Booking',
                'verbose_name_plural': 'Machine Bookings',
                'db_table': 'machine_bookings',
                'ordering': ['-work_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='machines.machinebooking'),
        ),
    ]
