# Generated by Django 5.2.17 on 2026-08-16 15:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
        ('finance', '0004_dailyclosing'),
        ('machines', '0003_machinebooking_machineworkentry_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineMaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(help_text='Service schedule title (e.g. 250 Hour Engine Oil & Filter Change)', max_length=150)),
                ('service_basis', models.CharField(choices=[('METER', 'Meter-Based (Hours/KM)'), ('DATE', 'Calendar Date-Based'), ('BOTH', 'Both (Whichever comes first)')], db_index=True, default='METER', max_length=10)),
                ('service_interval_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Service interval in meter units (e.g. 250.00 hours or 5000.00 km)', max_digits=10, null=True)),
                ('service_interval_days', models.IntegerField(blank=True, help_text='Service interval in calendar days (e.g. 90 days)', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Meter reading at last completed service', max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated next service meter reading', max_digits=10, null=True)),
                ('warning_meter_before', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text="Trigger 'Due Soon' this many meter units before next service", max_digits=10)),
                ('warning_days_before', models.IntegerField(default=7, help_text="Trigger 'Due Soon' this many days before next service date")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_schedules', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'db_table': 'machine_maintenance_schedules',
                'ordering': ['machine', 'schedule_name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE_SERVICE', 'Preventive Periodic Service'), ('BREAKDOWN_REPAIR', 'Field Breakdown Repair'), ('CORRECTIVE_REPAIR', 'Corrective / Scheduled Repair'), ('INSPECTION', 'Safety / Seasonal Inspection'), ('TYRE_SERVICE', 'Tyre & Wheel Service'), ('ELECTRICAL', 'Electrical & Wiring Repair'), ('ENGINE', 'Engine Overhaul / Service'), ('HYDRAULIC', 'Hydraulic System Repair'), ('TRANSMISSION', 'Transmission & Clutch Service'), ('OTHER', 'Other Maintenance')], db_index=True, default='PREVENTIVE_SERVICE', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Reported / Open'), ('DIAGNOSING', 'Diagnosing Problem'), ('WAITING_FOR_PARTS', 'Waiting for Spare Parts'), ('IN_REPAIR', 'In Repair / Workshop'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=25)),
                ('reported_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Current meter reading at time of maintenance/breakdown', max_digits=10, null=True)),
                ('problem_description', models.TextField(help_text='Reported issue or scheduled service reason')),
                ('diagnosis', models.TextField(blank=True, help_text='Mechanic/Workshop diagnosis', null=True)),
                ('work_performed', models.TextField(blank=True, help_text='Summary of repairs and services completed', null=True)),
                ('breakdown_location', models.CharField(blank=True, help_text='Field / Village / Road location of breakdown', max_length=200, null=True)),
                ('breakdown_time', models.DateTimeField(blank=True, null=True)),
                ('machine_stopped', models.BooleanField(db_index=True, default=False, help_text='If True, machine is halted and must be blocked from operational dispatch')),
                ('severity', models.CharField(choices=[('LOW', 'Low (Minor / Cosmetic)'), ('MEDIUM', 'Medium (Needs Attention)'), ('HIGH', 'High (Operational Impact)'), ('CRITICAL', 'Critical (Machine Stopped / Field Emergency)')], default='MEDIUM', max_length=15)),
                ('external_workshop_name', models.CharField(blank=True, help_text='Name of external repair workshop if not registered as Supplier', max_length=150, null=True)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all spare parts used', max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='In-house or external labor cost', max_digits=15)),
                ('external_service_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='External workshop / lathe / specialist charges', max_digits=15)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Towing, transport, oils, misc expenses', max_digits=15)),
                ('total_maintenance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative total = parts + labor + external + other', max_digits=15)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_jobs', to=settings.AUTH_USER_MODEL)),
                ('linked_expense', models.OneToOneField(blank=True, help_text='Linked financial Expense record if explicitly posted by Owner/Accountant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_job', to='expenses.expense')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_jobs', to='machines.machine')),
                ('maintenance_schedule', models.ForeignKey(blank=True, help_text='Optional link to preventive service schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='machines.machinemaintenanceschedule')),
                ('supplier', models.ForeignKey(blank=True, help_text='External workshop or parts vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Maintenance Job',
                'verbose_name_plural': 'Maintenance Jobs',
                'db_table': 'machine_maintenance_jobs',
                'ordering': ['-reported_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(db_index=True, help_text='Name/description of spare part (e.g. Engine Oil Filter)', max_length=150)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer / OEM part number', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of parts/litres consumed', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit in INR', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative item total = quantity * unit_cost', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='machines.maintenancejob')),
                ('supplier', models.ForeignKey(blank=True, help_text='Vendor who supplied this spare part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_part_usages', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Maintenance Part Usage',
                'verbose_name_plural': 'Maintenance Part Usages',
                'db_table': 'machine_maintenance_part_usages',
                'ordering': ['id'],
            },
        ),
    ]
