# Generated by Django 5.2.17 on 2026-08-31 18:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dailyclosing'),
        ('machines', '0006_alter_maintenancejob_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedHarvesterOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Full Name of Harvester Owner', max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Company commission % on gross harvesting billing', max_digits=5)),
                ('standard_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('2400.00'), help_text='Default farmer cutting rate per hour in INR', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rented Harvester Owner',
                'verbose_name_plural': 'Rented Harvester Owners',
                'db_table': 'rented_harvester_owners',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2400.00'), help_text='Standard hourly commercial rate in INR (e.g. ₹2,400/hr)', max_digits=12),
        ),
        migrations.AddField(
            model_name='machine',
            name='ownership_type',
            field=models.CharField(choices=[('COMPANY_OWNED', 'Company Owned Fleet'), ('RENTED', 'Rented Fleet (Third-Party Owner)')], db_index=True, default='COMPANY_OWNED', max_length=20),
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance / cash collected on site in INR', max_digits=15),
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='manual_bill_no',
            field=models.CharField(blank=True, help_text='Manual voucher / bill number (optional)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash in Hand'), ('UPI', 'UPI / Digital Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('UDHAR', 'Udhar (Credit)'), ('SPLIT', 'Advance + Udhar')], db_index=True, default='UDHAR', max_length=20),
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='receivable',
            field=models.ForeignKey(blank=True, help_text='Linked Customer Receivable for farmer ledger tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvesting_work_entries', to='finance.receivable'),
        ),
        migrations.AddField(
            model_name='machineworkentry',
            name='udhar_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit balance added to Farmer Udhar Katha in INR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text='Equipment name / Model (e.g. John Deere 5310, Class Crop Tiger 37)', max_length=100),
        ),
        migrations.CreateModel(
            name='HarvesterCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('vehicle_name', models.CharField(help_text='e.g. Tata 1613 Harvester Transport Truck, Class Crop Tiger 37', max_length=100)),
                ('registration_no', models.CharField(db_index=True, help_text='e.g. KA-36 TR 9901', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRANSPORT_TRUCK', 'Harvester Transport Truck'), ('COMBINE_HARVESTER', 'Combine Harvester'), ('TIPPING_TRAILER', 'Heavy Tipping Trailer')], db_index=True, default='TRANSPORT_TRUCK', max_length=30)),
                ('owner_name', models.CharField(default='Sri Basaveshwara Fleet', help_text='Fleet or Rented Owner Name', max_length=100)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_policy_no', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('road_tax_receipt_no', models.CharField(blank=True, max_length=100, null=True)),
                ('road_tax_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('nc_permit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('nc_permit_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('fitness_cert_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('puc_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='machines.machine')),
                ('rented_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='machines.rentedharvesterowner')),
            ],
            options={
                'verbose_name': 'Harvester & Transport Compliance',
                'verbose_name_plural': 'Harvester & Transport Compliances',
                'db_table': 'harvester_compliance',
                'ordering': ['registration_no'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='rented_owner',
            field=models.ForeignKey(blank=True, help_text='Assigned owner if this is a seasonal rented harvester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machines.rentedharvesterowner'),
        ),
        migrations.CreateModel(
            name='RentedHarvesterSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('gross_earnings', models.DecimalField(decimal_places=2, help_text='Gross bill amount from harvesting work entry', max_digits=15)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Company commission percentage', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('diesel_liters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diesel liters provided from company stock', max_digits=10)),
                ('diesel_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diesel cost deducted from owner settlement in INR', max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other operational deductions in INR', max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, help_text='Net payable to owner = Gross - Commission - Diesel - Other', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payout'), ('SETTLED', 'Settled / Paid to Owner')], db_index=True, default='PENDING', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, help_text='Bank UTR / Cash Voucher No', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='machines.rentedharvesterowner')),
                ('work_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvester_settlement', to='machines.machineworkentry')),
            ],
            options={
                'verbose_name': 'Rented Harvester Settlement',
                'verbose_name_plural': 'Rented Harvester Settlements',
                'db_table': 'rented_harvester_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
