# Generated by Django 5.2.17 on 2026-08-15 10:53

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash In Hand / Cash Box'), ('BANK_SAVINGS', 'Bank Savings Account'), ('BANK_CURRENT', 'Bank Current Account'), ('UPI_WALLET', 'UPI / Digital Wallet'), ('PETTY_CASH', 'Petty Cash Box')], db_index=True, default='BANK_CURRENT', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_balance_date', models.DateField(default=django.utils.timezone.now)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derived cached balance. Single source of truth is account_transactions.', max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Account',
                'verbose_name_plural': 'Business Accounts',
                'db_table': 'accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('supplier_type', models.CharField(choices=[('FUEL_PUMP', 'Fuel Pump / Petroleum Outlet'), ('SPARE_PARTS', 'Spare Parts Vendor'), ('WORKSHOP', 'Repair Workshop'), ('FERTILIZER', 'Fertilizer & Seeds Dealer'), ('OTHER', 'General Supplier')], db_index=True, default='SPARE_PARTS', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
    ]
