# Generated by Django 5.2.17 on 2026-08-15 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance Setup'), ('INCOME', 'Direct Income / Revenue'), ('EXPENSE', 'Operational / General Expense'), ('RECEIVABLE_PAYMENT', 'Customer Receivable Payment'), ('PAYABLE_PAYMENT', 'Supplier Payable Payment'), ('EMPLOYEE_PAYMENT', 'Employee Wage / Advance Payout'), ('TRANSFER_IN', 'Inter-Account Transfer (Inflow)'), ('TRANSFER_OUT', 'Inter-Account Transfer (Outflow)'), ('ADJUSTMENT', 'Audit / Ledger Adjustment'), ('REVERSAL', 'Transaction Reversal / Correction')], db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit (Money Out)'), ('CREDIT', 'Credit (Money In)')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(blank=True, help_text='e.g. Expense, CustomerPayment, FuelEntry', max_length=50, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_transactions', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Ledger Transaction',
                'verbose_name_plural': 'Account Ledger Transactions',
                'db_table': 'account_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
