# Generated by Django 5.2.17 on 2026-08-15 11:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
        ('finance', '0002_accounttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_type',
            field=models.CharField(blank=True, help_text='e.g. Expense, CustomerPayment, SupplierPayment, FuelEntry', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bill_no', models.CharField(blank=True, help_text='Vendor Invoice / Bill No.', max_length=50, null=True)),
                ('bill_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid / Settled')], db_index=True, default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payables', to=settings.AUTH_USER_MODEL)),
                ('linked_expense', models.ForeignKey(blank=True, help_text='Originating credit expense (if created via credit purchase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payables', to='expenses.expense')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payables', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payable',
                'verbose_name_plural': 'Supplier Payables',
                'db_table': 'payables',
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('invoice_no', models.CharField(blank=True, help_text='Bill / Invoice Number', max_length=50, null=True)),
                ('bill_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid / Settled')], db_index=True, default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receivables', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receivables', to='finance.customer')),
            ],
            options={
                'verbose_name': 'Customer Receivable',
                'verbose_name_plural': 'Customer Receivables',
                'db_table': 'receivables',
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('UPI', 'UPI / QR Payment'), ('CHEQUE', 'Cheque')], db_index=True, default='CASH', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='UTR / Receipt / Cheque No.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_receipts', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('linked_ledger_transaction', models.OneToOneField(blank=True, help_text='Linked central ledger inflow entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='finance.accounttransaction')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='finance.receivable')),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'db_table': 'customer_payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('UPI', 'UPI Transfer'), ('CHEQUE', 'Cheque')], db_index=True, default='BANK_TRANSFER', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='UTR / Cheque / Voucher Ref', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supplier_payouts', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('linked_ledger_transaction', models.OneToOneField(blank=True, help_text='Linked central ledger debit entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payment', to='finance.accounttransaction')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='finance.payable')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'db_table': 'supplier_payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
