# Generated by Django 5.2.17 on 2026-08-15 11:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_accounttransaction_reference_type_payable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('scope', models.CharField(choices=[('CASH_ACCOUNT', 'Cash Account Physical Closing'), ('BANK_ACCOUNT', 'Bank Account Reconciliation'), ('UPI_ACCOUNT', 'UPI / Wallet Reconciliation'), ('CONSOLIDATED', 'Consolidated Liquid Closing')], db_index=True, default='CONSOLIDATED', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfer_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfer_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_closing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_closing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('BALANCED', 'Balanced (Zero Discrepancy)'), ('SURPLUS', 'Surplus Cash / Excess Funds'), ('DEFICIT', 'Deficit Cash / Shortage Funds')], db_index=True, default='BALANCED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Mandatory explanation if discrepancy != 0', null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Specific account (NULL if CONSOLIDATED)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='daily_closings', to='finance.account')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_financial_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Financial Closing',
                'verbose_name_plural': 'Daily Financial Closings',
                'db_table': 'daily_closings',
                'ordering': ['-closing_date', '-id'],
                'unique_together': {('closing_date', 'scope', 'account')},
            },
        ),
    ]
