# Generated by Django 5.2.17 on 2026-08-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_expense'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. August 2026 Fleet Operations Budget', max_length=100)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True, help_text='Month (1-12)')),
                ('period_year', models.PositiveSmallIntegerField(db_index=True, help_text='Year (e.g. 2026)')),
                ('business_segment', models.CharField(choices=[('GENERAL', 'General Combined Operations'), ('FARM_OPERATIONS', 'Farm Operations & Cultivation'), ('MACHINERY_RENTAL', 'Machinery Custom Hiring & Rental'), ('WORKSHOP_REPAIRS', 'Workshop & Fleet Maintenance'), ('SHOP_RETAIL', 'Retail Counter & Agrochemicals'), ('GENERAL_ADMIN', 'General Administration & Overhead')], db_index=True, default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'ordering': ['-period_year', '-period_month', 'title'],
                'unique_together': {('period_month', 'period_year', 'business_segment')},
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budget_items', to='expenses.expensecategory')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Budget Allocation Item',
                'verbose_name_plural': 'Budget Allocation Items',
                'db_table': 'budget_items',
                'ordering': ['category__name', 'machine__machine_code'],
                'unique_together': {('budget', 'category', 'machine')},
            },
        ),
    ]
