# Generated by Django 5.2.17 on 2026-09-03 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Sri Basaveshwara Harvesting & Co', help_text='Primary business trade name', max_length=150)),
                ('legal_name', models.CharField(blank=True, default='Sri Basaveshwara Agricultural Contractor Services', help_text='Registered legal entity name', max_length=200)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(blank=True, default='contact@basaveshwara-harvesting.com', max_length=100)),
                ('village', models.CharField(blank=True, default='Harapanahalli Road', max_length=100)),
                ('taluk', models.CharField(blank=True, default='Harapanahalli', max_length=100)),
                ('district', models.CharField(blank=True, default='Vijayanagara', max_length=100)),
                ('state', models.CharField(blank=True, default='Karnataka', max_length=100)),
                ('pin_code', models.CharField(blank=True, default='583131', max_length=20)),
                ('gst_number', models.CharField(blank=True, help_text='GSTIN if applicable', max_length=30, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='PAN / State Tax ID', max_length=30, null=True)),
                ('authorized_signatory_name', models.CharField(blank=True, default='Managing Partner', max_length=100)),
                ('authorized_signatory_designation', models.CharField(blank=True, default='Authorized Signatory', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='ReportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FARMER_STATEMENT', 'Farmer Account Statement PDF'), ('PAYMENT_RECEIPT', 'Payment / Advance Receipt PDF'), ('WORK_INVOICE', 'Work Entry / Invoice PDF'), ('MACHINERY_PNL', 'Machinery Operational P&L PDF'), ('EXPENSE_ANALYSIS', 'Expense Analysis PDF'), ('RECEIVABLES_AGING', 'Farmer Receivables Aging PDF'), ('FINANCIAL_AUDIT', 'Financial Audit Statement PDF')], db_index=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_object_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('report_period_start', models.DateField(blank=True, null=True)),
                ('report_period_end', models.DateField(blank=True, null=True)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Audit Log',
                'verbose_name_plural': 'Report Audit Logs',
                'db_table': 'report_audit_logs',
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
