# Generated by Django 5.2.17 on 2026-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_account_no',
            field=models.CharField(blank=True, help_text='Bank account number for invoice payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for invoices', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, default='Agricultural Harvesting & Heavy Equipment Fleet Hub', help_text='Tagline or subtitle appearing under company name', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI VPA / QR payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, default='+91 98801 99000', max_length=50),
        ),
    ]
