# Generated by Django 5.2.17 on 2026-08-15 10:53

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('TRACTOR_DRIVER', 'Tractor Driver / Machine Operator'), ('HARVESTER_OPERATOR', 'Harvester Specialist'), ('WORKSHOP_MECHANIC', 'Workshop Mechanic / Technician'), ('SHOP_STAFF', 'Retail & Shop Staff'), ('ACCOUNTANT', 'Accountant / Cashier'), ('MANAGER', 'Operations Manager / Supervisor'), ('DAILY_LABOR', 'Daily Field Labor')], db_index=True, default='TRACTOR_DRIVER', max_length=30)),
                ('wage_type', models.CharField(choices=[('MONTHLY_SALARY', 'Monthly Fixed Salary'), ('DAILY_WAGE', 'Daily Wage (Per Day Rate)'), ('PER_ACRE_COMMISSION', 'Per Acre Commission')], db_index=True, default='DAILY_WAGE', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base rate in INR (Monthly salary, daily wage, or per-acre rate)', max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ACTIVE', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
    ]
