# Generated by Django 5.2.17 on 2026-08-15 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('finance', '0002_accounttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('SALARY_ACCRUAL', 'Salary / Wage Accrual (Liability Earned)'), ('ADVANCE_PAYOUT', 'Advance Payout (Money Out)'), ('SALARY_SETTLEMENT', 'Salary Settlement Payout (Money Out)'), ('BONUS', 'Performance Bonus / Festival Payout (Money Out)')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Financial amount in INR', max_digits=15)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('UPI', 'UPI Transfer'), ('CHEQUE', 'Cheque')], db_index=True, default='CASH', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='Voucher / Bank UTR / Receipt No.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_payouts', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_payments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='employees.employee')),
                ('linked_ledger_transaction', models.OneToOneField(blank=True, help_text='Linked central ledger entry for actual bank/cash movements', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payment', to='finance.accounttransaction')),
            ],
            options={
                'verbose_name': 'Employee Wage / Payment',
                'verbose_name_plural': 'Employee Wages & Payments',
                'db_table': 'employee_payments',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
