# Generated by Django 5.2.17 on 2026-08-15 15:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='units_logged',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of units (days/acres/months) logged (e.g. 25 days @ ₹200.00)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='[LEGACY] Authoritative source is EmployeeCompensation.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('MONTHLY_SALARY', 'Monthly Fixed Salary'), ('DAILY_WAGE', 'Daily Wage (Per Day Rate)'), ('PER_ACRE_COMMISSION', 'Per Acre Commission')], db_index=True, default='DAILY_WAGE', help_text='[LEGACY] Authoritative source is EmployeeCompensation.', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_type', models.CharField(choices=[('MONTHLY_SALARY', 'Monthly Fixed Salary'), ('DAILY_WAGE', 'Daily Wage (Per Day Rate)'), ('PER_ACRE_COMMISSION', 'Per Acre Commission')], db_index=True, help_text='Type of compensation', max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Authoritative compensation rate amount in INR', max_digits=15)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date from which this compensation rate is effective')),
                ('effective_to', models.DateField(blank=True, db_index=True, help_text='Date until which this rate was effective (null if currently active)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this compensation is currently active')),
                ('notes', models.CharField(blank=True, help_text='Context / remarks (e.g. Standard Field Allowance, Base Retainer)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Associated staff member', on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Compensation',
                'verbose_name_plural': 'Employee Compensations',
                'db_table': 'employee_compensations',
                'ordering': ['-is_active', '-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='compensation',
            field=models.ForeignKey(blank=True, help_text='Authoritative compensation structure applied for this payment/accrual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payments', to='employees.employeecompensation'),
        ),
    ]
