# Generated by Django 5.2.17 on 2026-08-15 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('expenses', '0001_initial'),
        ('finance', '0002_accounttransaction'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('UPI', 'UPI / QR Code'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit / Pay Later (Payable)')], db_index=True, default='CASH', max_length=20)),
                ('business_segment', models.CharField(choices=[('GENERAL', 'General Business'), ('FARM_OPERATIONS', 'Farm Operations / Cultivation'), ('MACHINERY_RENTAL', 'Machinery Custom Hiring Hub'), ('WORKSHOP_REPAIRS', 'Workshop & Service Center'), ('SHOP_RETAIL', 'Agri Inputs Retail Store'), ('GENERAL_ADMIN', 'Administrative & Overhead')], db_index=True, default='GENERAL', max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_quick_expense', models.BooleanField(default=False)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expenses', to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expenses', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_expenses', to='employees.employee')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='machines.machine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
